# Generated by Django 5.0.2 on 2024-02-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type_item',
            field=models.CharField(choices=[('ESPORTIVO', 'ESPORTIVO'), ('CONVERSIVEL', 'CONVERSIVEL'), ('SUV', 'SUV')], max_length=100),
        ),
    ]
